/**
 * Scenario 4 report-grade analyzer
 *
 * Consumes outputs of scripts/exhaustive-s4-outcomes.ts and produces
 * report-ready CSV/JSON/Markdown tables without re-implementing adjudication.
 *
 * Recommended inputs:
 *   1) one full-path exhaustive run (worlds=1, NOT --summary-only)
 *   2) one robustness run (worlds=3 or more, --summary-only)
 *
 * Usage:
 *   npx tsx scripts/analyze-s4-report.ts \
 *     --structural-summary analysis/s4-report-structural/summary.json \
 *     --paths analysis/s4-report-structural/all-paths.csv.gz \
 *     --robustness-summary analysis/s4-report-robustness/summary.json \
 *     --out-dir analysis/s4-report-analysis
 *
 * The percentages produced here are DESIGN/SIMULATION shares, not empirical
 * real-world probabilities. See methodology-fa.md generated by this script.
 */

import fs from "node:fs";
import path from "node:path";
import readline from "node:readline";
import { createGunzip } from "node:zlib";

const END_STATES = [
  "escalation_spiral",
  "intelligence_failure",
  "coalition_fracture",
  "negotiated_deescalation",
  "calm_crisis_control",
  "costly_deterrence",
  "persistent_ambiguity",
  "strategic_information_opportunity",
  "mixed_crisis_containment",
] as const;

type EndState = (typeof END_STATES)[number];

const END_STATE_FA: Record<string, string> = {
  escalation_spiral: "مارپیچ تشدید",
  intelligence_failure: "شکست اطلاعاتی",
  coalition_fracture: "شکاف ائتلافی",
  negotiated_deescalation: "کاهش تنش مذاکره‌شده",
  calm_crisis_control: "مهار آرام بحران",
  costly_deterrence: "بازدارندگی پرهزینه",
  persistent_ambiguity: "ابهام پایدار",
  strategic_information_opportunity: "فرصت اطلاعاتی راهبردی",
  mixed_crisis_containment: "مهار نسبی بحران",
};

const INTENT_WEIGHTS: Record<string, number> = {
  probe: 0.30,
  intelligence_collection: 0.25,
  coercion: 0.20,
  alliance_fracture: 0.15,
  benign_ambiguous: 0.10,
};

const INTENT_FA: Record<string, string> = {
  probe: "آزمون آستانه‌ها",
  intelligence_collection: "جمع‌آوری اطلاعات",
  coercion: "اعمال فشار",
  alliance_fracture: "ایجاد شکاف ائتلافی",
  benign_ambiguous: "رفتار مبهم/غیرخصمانه",
};

const DECISION_FIELDS = [
  ["m1_information", "مرحله ۱ / اطلاعات"],
  ["m1_protection", "مرحله ۱ / حفاظت"],
  ["m1_communication", "مرحله ۱ / ارتباط"],
  ["m2_investigation", "مرحله ۲ / بررسی علت"],
  ["m2_mission", "مرحله ۲ / تداوم مأموریت"],
  ["m2_response", "مرحله ۲ / پاسخ"],
  ["m3_threshold", "مرحله ۳ / آستانه اقدام"],
  ["m3_coa", "مرحله ۳ / مسیر اقدام"],
  ["m3_information", "مرحله ۳ / سیاست اطلاعاتی"],
  ["m3_offramp", "مرحله ۳ / مسیر کاهش تنش"],
] as const;

const OPTION_FA: Record<string, string> = {
  m1_i_passive: "پایش مستمر با ظرفیت موجود",
  m1_i_dedicated_ssa: "تخصیص پایش اختصاصی SSA",
  m1_i_commercial: "اعتبارسنجی با داده تجاری مستقل",
  m1_i_allied_network: "فعال‌سازی شبکه اطلاعاتی متحدان",
  m1_p_hold: "عدم تغییر وضعیت حفاظتی",
  m1_p_covert_readiness: "افزایش آمادگی پنهان",
  m1_p_visible_protection: "حفاظت آشکار و برگشت‌پذیر",
  m1_p_mission_reposition: "بازآرایی محسوس مأموریت",
  m1_c_none: "عدم ارسال پیام",
  m1_c_private: "تنش‌زدایی خصوصی",
  m1_c_allies: "هماهنگی با متحدان",
  m1_c_public_warning: "هشدار عمومی",
  m1_c_private_allied: "تماس خصوصی همراه هماهنگی محدود متحدان",
  m2_a_technical_diagnostics: "عیب‌یابی فنی",
  m2_a_second_sensor: "اعتبارسنجی با حسگر دوم",
  m2_a_ally_intel: "درخواست اطلاعات متحد",
  m2_a_commercial_validation: "اعتبارسنجی تجاری",
  m2_a_act_with_current_data: "اقدام با داده موجود",
  m2_m_continue_normal: "ادامه مأموریت عادی",
  m2_m_activate_fallback: "فعال‌سازی ظرفیت پشتیبان",
  m2_m_reduce_load: "کاهش بار مأموریت",
  m2_m_protective_reconfiguration: "بازآرایی حفاظتی",
  m2_m_split_service: "تقسیم سرویس",
  m2_r_no_counteraction: "عدم اقدام متقابل",
  m2_r_request_explanation: "درخواست توضیح رسمی",
  m2_r_private_warning: "هشدار خصوصی",
  m2_r_joint_allied_response: "پاسخ مشترک با متحدان",
  m2_r_request_defensive_authority: "درخواست اختیار دفاعی",
  m2_r_deconfliction_offer: "پیشنهاد رفع اصطکاک/فاصله‌گذاری",
  m3_t_insufficient: "شواهد برای اقدام کافی نیست",
  m3_t_sufficient_limited: "برای اقدام محدود و برگشت‌پذیر کافی است",
  m3_t_sufficient_strong: "برای اقدام گسترده‌تر کافی است",
  m3_coa_contain_understand: "مهار و شناخت",
  m3_coa_controlled_deterrence: "بازدارندگی کنترل‌شده",
  m3_coa_coordinated_response: "پاسخ هماهنگ ائتلافی",
  m3_coa_negotiated_deescalation: "کاهش تنش مذاکره‌شده",
  m3_coa_unilateral_strong: "اقدام یک‌جانبه قوی‌تر",
  m3_info_keep_restricted: "حفظ اطلاعات در سطح محدود",
  m3_info_share_allies: "اشتراک با متحدان",
  m3_info_public_partial: "انتشار عمومی جزئی",
  m3_info_public_attribution: "انتساب عمومی",
  accept_as_interim: "پذیرش موقت",
  renegotiate_terms: "مذاکره مجدد شروط",
  keep_channel_open_no_commitment: "باز نگه‌داشتن کانال بدون تعهد",
  reject: "رد مسیر کاهش تنش",
};

const ACTOR_FIELDS = [
  "m1_red_action",
  "m1_ally_action",
  "m1_commercial_action",
  "m2_red_action",
  "m2_ally_action",
  "m2_commercial_action",
  "m3_red_action",
  "m3_ally_action",
] as const;

const NUMERIC_FIELDS = [
  "mission_continuity",
  "situation_awareness",
  "escalation_pressure",
  "operational_readiness",
  "coalition_cohesion",
  "information_exposure",
  "strategic_legitimacy",
  "ssa_capacity",
  "protective_capacity",
  "political_capital",
  "disclosure_budget",
  "metric_mission",
  "metric_information_quality",
  "metric_escalation_control",
  "metric_coalition",
  "metric_resource_sustainability",
  "metric_information_discipline",
  "metric_legitimacy",
  "metric_resilience",
  "metric_reversibility",
  "metric_decision_coherence",
] as const;

function arg(name: string): string | undefined {
  const i = process.argv.indexOf(name);
  return i >= 0 ? process.argv[i + 1] : undefined;
}

const structuralSummaryPath = arg("--structural-summary");
const robustnessSummaryPath = arg("--robustness-summary") ?? structuralSummaryPath;
const pathsGzPath = arg("--paths");
const outDir = path.resolve(arg("--out-dir") ?? "analysis/scenario4-report-analysis");
const topN = Number(arg("--top-n") ?? "10");

if (!structuralSummaryPath) {
  throw new Error("Required: --structural-summary <summary.json>");
}

fs.mkdirSync(outDir, { recursive: true });

const readJson = (p: string) => JSON.parse(fs.readFileSync(path.resolve(p), "utf8"));
const structural = readJson(structuralSummaryPath);
const robustness = robustnessSummaryPath ? readJson(robustnessSummaryPath) : structural;

const csvCell = (v: unknown) => {
  if (v === undefined || v === null) return "";
  const s = String(v);
  return /[",\n\r]/.test(s) ? `"${s.replaceAll('"', '""')}"` : s;
};

function writeCsv(name: string, rows: Array<Record<string, unknown>>) {
  const out = path.join(outDir, name);
  if (!rows.length) {
    fs.writeFileSync(out, "", "utf8");
    return;
  }
  const cols = Array.from(new Set(rows.flatMap((r) => Object.keys(r))));
  const lines = [cols.map(csvCell).join(",")];
  for (const r of rows) lines.push(cols.map((c) => csvCell(r[c])).join(","));
  fs.writeFileSync(out, lines.join("\n") + "\n", "utf8");
}

const sum = (xs: number[]) => xs.reduce((a, b) => a + b, 0);
const mean = (xs: number[]) => (xs.length ? sum(xs) / xs.length : 0);
const std = (xs: number[]) => {
  if (xs.length <= 1) return 0;
  const m = mean(xs);
  return Math.sqrt(xs.reduce((a, x) => a + (x - m) ** 2, 0) / xs.length);
};
const pct = (x: number) => x * 100;

function endTotal(counter: Record<string, number>) {
  return END_STATES.reduce((a, e) => a + Number(counter?.[e] ?? 0), 0);
}

// 1) Structural end-state distribution
const structuralTotal = Number(structural.totalPaths ?? endTotal(structural.endStates ?? {}));
const overallRows = END_STATES.map((e) => {
  const count = Number(structural.endStates?.[e] ?? 0);
  return {
    end_state: e,
    end_state_fa: END_STATE_FA[e],
    count,
    share: structuralTotal ? count / structuralTotal : 0,
    percent: structuralTotal ? pct(count / structuralTotal).toFixed(3) : "0.000",
    reachable: count > 0,
  };
});
writeCsv("01_end_states_structural.csv", overallRows);

// 2) By intent
const intentRows: Array<Record<string, unknown>> = [];
for (const [intent, counter] of Object.entries(structural.byIntent ?? {})) {
  const total = endTotal(counter as Record<string, number>);
  for (const e of END_STATES) {
    const count = Number((counter as any)[e] ?? 0);
    intentRows.push({
      intent,
      intent_fa: INTENT_FA[intent] ?? intent,
      design_weight: INTENT_WEIGHTS[intent] ?? null,
      end_state: e,
      end_state_fa: END_STATE_FA[e],
      count,
      intent_total_paths: total,
      within_intent_share: total ? count / total : 0,
      within_intent_percent: total ? pct(count / total).toFixed(3) : "0.000",
    });
  }
}
writeCsv("02_end_states_by_intent.csv", intentRows);

// 3) Intent-weighted design distribution
const weightedRows = END_STATES.map((e) => {
  let weightedShare = 0;
  let weightUsed = 0;
  const contributions: string[] = [];
  for (const [intent, weight] of Object.entries(INTENT_WEIGHTS)) {
    const counter = structural.byIntent?.[intent];
    if (!counter) continue;
    const total = endTotal(counter);
    if (!total) continue;
    const conditional = Number(counter[e] ?? 0) / total;
    weightedShare += weight * conditional;
    weightUsed += weight;
    contributions.push(`${intent}:${(100 * weight * conditional).toFixed(3)}pp`);
  }
  if (weightUsed && Math.abs(weightUsed - 1) > 1e-9) weightedShare /= weightUsed;
  return {
    end_state: e,
    end_state_fa: END_STATE_FA[e],
    weighted_design_share: weightedShare,
    weighted_design_percent: pct(weightedShare).toFixed(3),
    contribution_by_intent: contributions.join(" | "),
    interpretation: "سهم طراحی وزن‌دار؛ نه احتمال تجربی دنیای واقعی",
  };
});
writeCsv("03_end_states_intent_weighted.csv", weightedRows);

// 4) World robustness
const byWorldRows: Array<Record<string, unknown>> = [];
const sharesByEnd: Record<string, number[]> = Object.fromEntries(END_STATES.map((e) => [e, []]));
for (const [world, counter] of Object.entries(robustness.byWorld ?? {})) {
  const total = endTotal(counter as Record<string, number>);
  for (const e of END_STATES) {
    const count = Number((counter as any)[e] ?? 0);
    const share = total ? count / total : 0;
    sharesByEnd[e].push(share);
    byWorldRows.push({
      world,
      end_state: e,
      end_state_fa: END_STATE_FA[e],
      count,
      world_total_paths: total,
      share,
      percent: pct(share).toFixed(3),
    });
  }
}
writeCsv("04_end_states_by_world.csv", byWorldRows);

const robustnessRows = END_STATES.map((e) => {
  const xs = sharesByEnd[e];
  const min = xs.length ? Math.min(...xs) : 0;
  const max = xs.length ? Math.max(...xs) : 0;
  return {
    end_state: e,
    end_state_fa: END_STATE_FA[e],
    worlds: xs.length,
    mean_share: mean(xs),
    mean_percent: pct(mean(xs)).toFixed(3),
    min_percent: pct(min).toFixed(3),
    max_percent: pct(max).toFixed(3),
    spread_percentage_points: pct(max - min).toFixed(3),
    std_percentage_points: pct(std(xs)).toFixed(3),
    reachable_in_all_worlds: xs.length > 0 && xs.every((x) => x > 0),
  };
});
writeCsv("05_end_state_world_robustness.csv", robustnessRows);

// 5) Hidden worlds
writeCsv(
  "06_hidden_worlds.csv",
  (robustness.hiddenWorlds ?? []).map((x: any) => ({
    world: x.world,
    intent: x.intent,
    intent_fa: INTENT_FA[x.intent] ?? x.intent,
    incident_cause: x.incidentCause,
    true_incident_attribution: x.trueIncidentAttribution,
  })),
);

// 6) Confidence tables, if present
const confidenceRows: Array<Record<string, unknown>> = [];
function flattenConfidence(groupType: string, groups: Record<string, any> | undefined) {
  if (!groups) return;
  for (const [group, v] of Object.entries(groups)) {
    const row: Record<string, unknown> = {
      group_type: groupType,
      group,
      count: v.count,
      min: v.min,
      max: v.max,
      p05: v.p05,
      p25: v.p25,
      p50: v.p50,
      p75: v.p75,
      p95: v.p95,
    };
    for (const t of [35, 40, 45, 50, 55, 60, 70]) {
      row[`share_gte_${t}`] = v.thresholdCoverage?.[`gte${t}`]?.share ?? null;
      row[`percent_gte_${t}`] = v.thresholdCoverage?.[`gte${t}`]
        ? pct(v.thresholdCoverage[`gte${t}`].share).toFixed(3)
        : null;
    }
    confidenceRows.push(row);
  }
}
if (structural.confidence?.overall) flattenConfidence("overall", { overall: structural.confidence.overall });
flattenConfidence("intent", structural.confidence?.byIntent);
flattenConfidence("incident_cause", structural.confidence?.byIncidentCause);
writeCsv("07_confidence_distribution.csv", confidenceRows);

// 7) Resource tables, if present
const resourceRows: Array<Record<string, unknown>> = [];
for (const [phase, phaseData] of Object.entries(structural.resources?.phases ?? {})) {
  for (const [resource, v] of Object.entries((phaseData as any).resources ?? {})) {
    resourceRows.push({
      phase,
      resource,
      start_baseline: structural.resources?.baseline?.[resource] ?? null,
      count: (v as any).count,
      min: (v as any).min,
      mean: (v as any).mean,
      p05: (v as any).p05,
      p50: (v as any).p50,
      p95: (v as any).p95,
    });
  }
}
writeCsv("08_resource_distribution_by_phase.csv", resourceRows);

const resourceThresholdRows: Array<Record<string, unknown>> = [];
for (const [phase, phaseData] of Object.entries(structural.resources?.phases ?? {})) {
  const t = (phaseData as any).thresholdShares ?? {};
  resourceThresholdRows.push({
    phase,
    paths: (phaseData as any).paths,
    share_any_below_70: t.below70,
    percent_any_below_70: t.below70 != null ? pct(t.below70).toFixed(3) : null,
    share_any_below_50: t.below50,
    percent_any_below_50: t.below50 != null ? pct(t.below50).toFixed(3) : null,
    share_any_below_30: t.below30,
    percent_any_below_30: t.below30 != null ? pct(t.below30).toFixed(3) : null,
    share_any_zero: t.exactZero,
    percent_any_zero: t.exactZero != null ? pct(t.exactZero).toFixed(3) : null,
  });
}
writeCsv("09_resource_pressure_thresholds.csv", resourceThresholdRows);

const resourceByEndRows: Array<Record<string, unknown>> = [];
for (const [end, resGroup] of Object.entries(structural.resources?.byEndState ?? {})) {
  for (const [resource, v] of Object.entries(resGroup as any)) {
    resourceByEndRows.push({
      end_state: end,
      end_state_fa: END_STATE_FA[end] ?? end,
      resource,
      min: (v as any).min,
      mean: (v as any).mean,
      p05: (v as any).p05,
      p50: (v as any).p50,
      p95: (v as any).p95,
    });
  }
}
writeCsv("10_resources_by_end_state.csv", resourceByEndRows);

const pathCostRows: Array<Record<string, unknown>> = [];
for (const [kind, v] of Object.entries(structural.resources?.pathCost ?? {})) {
  pathCostRows.push({
    kind,
    min: (v as any).min,
    mean: (v as any).mean,
    p05: (v as any).p05,
    p50: (v as any).p50,
    p95: (v as any).p95,
    max: (v as any).max,
  });
}
writeCsv("11_resource_path_costs.csv", pathCostRows);

// 8) Representative paths from summary
const exampleRows: Array<Record<string, unknown>> = [];
for (const e of END_STATES) {
  const arr = structural.examples?.[e] ?? [];
  arr.slice(0, topN).forEach((x: any, i: number) => {
    exampleRows.push({
      end_state: e,
      end_state_fa: END_STATE_FA[e],
      rank: i + 1,
      world: x.world,
      intent: x.intent,
      intent_fa: INTENT_FA[x.intent] ?? x.intent,
      signature: x.signature,
      incident_cause: x.incidentCause,
      true_incident_attribution: x.trueIncidentAttribution,
      red_final_action: x.redFinalAction,
      mission: x.mission,
      escalation: x.escalation,
      coalition: x.coalition,
      information_quality: x.informationQuality,
      system_attribution_confidence: x.systemAttributionConfidence,
    });
  });
}
writeCsv("12_representative_paths.csv", exampleRows);

// 9) Design-balance metrics
const structuralShares = overallRows.map((r: any) => Number(r.share)).filter((x) => x > 0);
const H = -structuralShares.reduce((a, p) => a + p * Math.log(p), 0);
const normalizedEntropy = H / Math.log(END_STATES.length);
const hhi = structuralShares.reduce((a, p) => a + p * p, 0);
const dominant = overallRows.reduce((a: any, b: any) => (Number(a.share) >= Number(b.share) ? a : b));
const balanceRows = [{
  reachable_end_states: overallRows.filter((r: any) => r.reachable).length,
  total_end_states: END_STATES.length,
  normalized_shannon_entropy: normalizedEntropy,
  hhi,
  dominant_end_state: dominant.end_state,
  dominant_end_state_fa: dominant.end_state_fa,
  dominant_share: dominant.share,
  dominant_percent: dominant.percent,
  endings_below_1_percent: overallRows.filter((r: any) => Number(r.share) < 0.01).length,
}];
writeCsv("13_design_balance_metrics.csv", balanceRows);

// ---- Optional full-path streaming analysis ----

type CountMap = Record<string, number>;
const inc = (m: CountMap, k: string, n = 1) => { m[k] = (m[k] ?? 0) + n; };

function parseCsvLine(line: string): string[] {
  const out: string[] = [];
  let cur = "";
  let quoted = false;
  for (let i = 0; i < line.length; i++) {
    const ch = line[i];
    if (quoted) {
      if (ch === '"' && line[i + 1] === '"') { cur += '"'; i++; }
      else if (ch === '"') quoted = false;
      else cur += ch;
    } else {
      if (ch === ',') { out.push(cur); cur = ""; }
      else if (ch === '"') quoted = true;
      else cur += ch;
    }
  }
  out.push(cur);
  return out;
}

if (pathsGzPath) {
  const selectionCount: CountMap = {};
  const selectionEndCount: CountMap = {};
  const actorCount: CountMap = {};
  const actorEndCount: CountMap = {};
  const causeCount: CountMap = {};
  const causeEndCount: CountMap = {};
  const severityCount: CountMap = {};
  const severityEndCount: CountMap = {};
  const prefixCount: CountMap = {};
  const prefixEndCount: CountMap = {};
  const metricSum: Record<string, Record<string, number>> = {};
  const endCount: CountMap = {};
  const policyWeightedEnd: Record<string, number> = {};
  const policyWeightedByIntent: Record<string, Record<string, number>> = {};
  let policyWeightTotal = 0;
  let branchCorrectedWeightTotal = 0;
  let offRampExpandedRows = 0;
  let pathRows = 0;

  const input = fs.createReadStream(path.resolve(pathsGzPath)).pipe(createGunzip());
  const rl = readline.createInterface({ input, crlfDelay: Infinity });
  let headers: string[] | null = null;
  const idx: Record<string, number> = {};

  for await (const line of rl) {
    if (!headers) {
      headers = parseCsvLine(line);
      headers.forEach((h, i) => idx[h] = i);
      const required = ["end_state", "signature", ...DECISION_FIELDS.map(([f]) => f)];
      const missing = required.filter((h) => idx[h] == null);
      if (missing.length) throw new Error(`all-paths.csv.gz missing required columns: ${missing.join(", ")}`);
      continue;
    }
    if (!line) continue;
    const cells = parseCsvLine(line);
    const get = (name: string) => idx[name] == null ? "" : (cells[idx[name]] ?? "");
    const end = get("end_state");
    if (!end) continue;
    pathRows++;
    inc(endCount, end);

    // Raw exhaustive leaf counts over-weight branches where the conditional
    // off-ramp question exists because each such prefix expands into 4 leaves.
    // For a uniform-choice policy, each off-ramp leaf receives weight 1/4.
    const intent = get("intent");
    const offRamp = get("m3_offramp");
    const branchWeight = offRamp ? 0.25 : 1;
    const intentWeight = INTENT_WEIGHTS[intent] ?? (1 / Object.keys(INTENT_WEIGHTS).length);
    const policyWeight = branchWeight * intentWeight;
    if (offRamp) offRampExpandedRows++;
    branchCorrectedWeightTotal += branchWeight;
    policyWeightTotal += policyWeight;
    policyWeightedEnd[end] = (policyWeightedEnd[end] ?? 0) + policyWeight;
    policyWeightedByIntent[intent] ??= {};
    policyWeightedByIntent[intent][end] = (policyWeightedByIntent[intent][end] ?? 0) + branchWeight;

    for (const [field] of DECISION_FIELDS) {
      const option = get(field);
      if (!option) continue;
      inc(selectionCount, `${field}\t${option}`);
      inc(selectionEndCount, `${field}\t${option}\t${end}`);
    }

    for (const field of ACTOR_FIELDS) {
      const action = get(field);
      if (!action) continue;
      inc(actorCount, `${field}\t${action}`);
      inc(actorEndCount, `${field}\t${action}\t${end}`);
    }

    const cause = get("incident_cause");
    const truth = get("true_incident_attribution");
    const causeKey = `${cause}\t${truth}`;
    inc(causeCount, causeKey);
    inc(causeEndCount, `${causeKey}\t${end}`);

    const severity = get("move3_severity");
    if (severity) {
      inc(severityCount, severity);
      inc(severityEndCount, `${severity}\t${end}`);
    }

    const signature = get("signature");
    const segs = signature.split("|");
    const p1 = segs[0] ?? "";
    const p12 = segs.slice(0, 2).join("|");
    if (p1) {
      inc(prefixCount, `M1\t${p1}`);
      inc(prefixEndCount, `M1\t${p1}\t${end}`);
    }
    if (p12) {
      inc(prefixCount, `M1+M2\t${p12}`);
      inc(prefixEndCount, `M1+M2\t${p12}\t${end}`);
    }

    metricSum[end] ??= {};
    for (const field of NUMERIC_FIELDS) {
      if (idx[field] == null) continue;
      const v = Number(get(field));
      if (Number.isFinite(v)) metricSum[end][field] = (metricSum[end][field] ?? 0) + v;
    }

    if (pathRows % 500_000 === 0) process.stdout.write(`\rAnalyzed ${pathRows.toLocaleString()} path rows...`);
  }
  process.stdout.write("\n");

  const pathOverallShare: Record<string, number> = {};
  for (const e of END_STATES) pathOverallShare[e] = (endCount[e] ?? 0) / Math.max(1, pathRows);

  const policyRows = END_STATES.map((e) => ({
    end_state: e,
    end_state_fa: END_STATE_FA[e],
    weighted_mass: policyWeightedEnd[e] ?? 0,
    uniform_policy_intent_weighted_share: policyWeightTotal ? (policyWeightedEnd[e] ?? 0) / policyWeightTotal : 0,
    uniform_policy_intent_weighted_percent: policyWeightTotal ? pct((policyWeightedEnd[e] ?? 0) / policyWeightTotal).toFixed(3) : "0.000",
    interpretation: "وزن نیت 30/25/20/15/10 + انتخاب یکنواخت گزینه‌های بازیکن + تصحیح شاخه شرطی off-ramp؛ نه احتمال تجربی واقعی",
  }));
  writeCsv("14_uniform_policy_intent_weighted_end_states.csv", policyRows);

  writeCsv("15_branching_diagnostics.csv", [{
    raw_terminal_rows: pathRows,
    off_ramp_expanded_rows: offRampExpandedRows,
    off_ramp_expanded_share: offRampExpandedRows / Math.max(1, pathRows),
    branch_corrected_total_mass: branchCorrectedWeightTotal,
    intent_and_branch_weighted_total_mass: policyWeightTotal,
    note: "شاخه‌های دارای off-ramp چهار برگ دارند؛ در توزیع policy-neutral هر برگ وزن 1/4 می‌گیرد.",
  }]);

  const optionRows: Array<Record<string, unknown>> = [];
  for (const [key, selected] of Object.entries(selectionCount)) {
    const [field, option] = key.split("\t");
    const windowFa = DECISION_FIELDS.find(([f]) => f === field)?.[1] ?? field;
    for (const e of END_STATES) {
      const n = selectionEndCount[`${field}\t${option}\t${e}`] ?? 0;
      const conditional = selected ? n / selected : 0;
      const baseline = pathOverallShare[e] ?? 0;
      optionRows.push({
        decision_field: field,
        decision_window_fa: windowFa,
        option_id: option,
        option_fa: OPTION_FA[option] ?? option,
        selected_paths: selected,
        selected_share_of_all_paths: selected / Math.max(1, pathRows),
        end_state: e,
        end_state_fa: END_STATE_FA[e],
        paths_to_end_state: n,
        p_end_given_option: conditional,
        p_end_given_option_percent: pct(conditional).toFixed(3),
        overall_end_share: baseline,
        overall_end_percent: pct(baseline).toFixed(3),
        difference_percentage_points: pct(conditional - baseline).toFixed(3),
        lift: baseline > 0 ? conditional / baseline : null,
        note: "ارتباط در فضای شبیه‌سازی؛ تفسیر علّی مستقیم نشود",
      });
    }
  }
  writeCsv("16_option_end_state_association.csv", optionRows);

  const topOptionRows: Array<Record<string, unknown>> = [];
  for (const e of END_STATES) {
    const rows = optionRows
      .filter((r: any) => r.end_state === e)
      .sort((a: any, b: any) => Number(b.difference_percentage_points) - Number(a.difference_percentage_points))
      .slice(0, topN);
    rows.forEach((r, i) => topOptionRows.push({ rank: i + 1, ...r }));
  }
  writeCsv("17_top_option_associations_by_end_state.csv", topOptionRows);

  const actorRows: Array<Record<string, unknown>> = [];
  for (const [key, selected] of Object.entries(actorCount)) {
    const [field, action] = key.split("\t");
    for (const e of END_STATES) {
      const n = actorEndCount[`${field}\t${action}\t${e}`] ?? 0;
      actorRows.push({
        actor_field: field,
        action,
        action_paths: selected,
        end_state: e,
        end_state_fa: END_STATE_FA[e],
        paths_to_end_state: n,
        p_end_given_action: selected ? n / selected : 0,
        p_end_given_action_percent: selected ? pct(n / selected).toFixed(3) : "0.000",
      });
    }
  }
  writeCsv("18_actor_actions_by_end_state.csv", actorRows);

  const causeRows: Array<Record<string, unknown>> = [];
  for (const [key, selected] of Object.entries(causeCount)) {
    const [cause, truth] = key.split("\t");
    for (const e of END_STATES) {
      const n = causeEndCount[`${key}\t${e}`] ?? 0;
      causeRows.push({
        incident_cause: cause,
        true_incident_attribution: truth,
        cause_paths: selected,
        end_state: e,
        end_state_fa: END_STATE_FA[e],
        paths_to_end_state: n,
        p_end_given_cause: selected ? n / selected : 0,
        p_end_given_cause_percent: selected ? pct(n / selected).toFixed(3) : "0.000",
      });
    }
  }
  writeCsv("19_incident_cause_by_end_state.csv", causeRows);

  const severityRows: Array<Record<string, unknown>> = [];
  for (const [severity, selected] of Object.entries(severityCount)) {
    for (const e of END_STATES) {
      const n = severityEndCount[`${severity}\t${e}`] ?? 0;
      severityRows.push({
        severity,
        severity_paths: selected,
        end_state: e,
        end_state_fa: END_STATE_FA[e],
        paths_to_end_state: n,
        p_end_given_severity: selected ? n / selected : 0,
        p_end_given_severity_percent: selected ? pct(n / selected).toFixed(3) : "0.000",
      });
    }
  }
  writeCsv("20_severity_by_end_state.csv", severityRows);

  const prefixRows: Array<Record<string, unknown>> = [];
  for (const e of END_STATES) {
    for (const prefixType of ["M1", "M1+M2"]) {
      const candidates = Object.entries(prefixEndCount)
        .filter(([k]) => k.startsWith(`${prefixType}\t`) && k.endsWith(`\t${e}`))
        .map(([k, n]) => {
          const parts = k.split("\t");
          const prefix = parts[1];
          return { prefix, n };
        })
        .sort((a, b) => b.n - a.n)
        .slice(0, topN);
      candidates.forEach((x, i) => {
        const all = prefixCount[`${prefixType}\t${x.prefix}`] ?? 0;
        prefixRows.push({
          end_state: e,
          end_state_fa: END_STATE_FA[e],
          prefix_type: prefixType,
          rank: i + 1,
          route_prefix: x.prefix,
          paths_to_end_state: x.n,
          all_paths_with_prefix: all,
          p_end_given_prefix: all ? x.n / all : 0,
          p_end_given_prefix_percent: all ? pct(x.n / all).toFixed(3) : "0.000",
        });
      });
    }
  }
  writeCsv("21_top_route_prefixes_by_end_state.csv", prefixRows);

  const metricRows: Array<Record<string, unknown>> = [];
  for (const e of END_STATES) {
    const n = endCount[e] ?? 0;
    if (!n) continue;
    const row: Record<string, unknown> = { end_state: e, end_state_fa: END_STATE_FA[e], paths: n };
    for (const field of NUMERIC_FIELDS) {
      if (metricSum[e]?.[field] != null) row[`mean_${field}`] = metricSum[e][field] / n;
    }
    metricRows.push(row);
  }
  writeCsv("22_mean_state_and_metrics_by_end_state.csv", metricRows);

  fs.writeFileSync(path.join(outDir, "full-path-analysis-metadata.json"), JSON.stringify({ analyzedRows: pathRows, source: path.resolve(pathsGzPath) }, null, 2));
}

// Route legend
writeCsv("23_route_legend.csv", Object.entries(OPTION_FA).map(([option_id, label_fa]) => ({ option_id, label_fa })));

// Machine-readable rollup
const reportJson = {
  generatedAt: new Date().toISOString(),
  sources: {
    structuralSummary: path.resolve(structuralSummaryPath),
    robustnessSummary: robustnessSummaryPath ? path.resolve(robustnessSummaryPath) : null,
    allPaths: pathsGzPath ? path.resolve(pathsGzPath) : null,
  },
  methodologicalLabels: {
    structuralPercentages: "سهم مسیرهای تصمیم در پیمایش exhaustive؛ نه احتمال تجربی",
    intentWeightedPercentages: "سهم طراحی با وزن‌های نیت پنهان و فرض توزیع یکنواخت مسیرهای تصمیم؛ نه احتمال واقعی",
    worldRobustness: "حساسیت نتایج به seed/hidden world در مدل",
  },
  structuralEndStates: overallRows,
  intentWeightedEndStates: weightedRows,
  robustness: robustnessRows,
  designBalance: balanceRows[0],
  confidence: structural.confidence ?? null,
  resources: structural.resources ?? null,
};
fs.writeFileSync(path.join(outDir, "report-study.json"), JSON.stringify(reportJson, null, 2), "utf8");

const topOverall = [...overallRows].sort((a: any, b: any) => Number(b.share) - Number(a.share));
const md = `# خروجی تحلیلی شبیه‌سازی سناریو ۴\n\n` +
`## هشدار روش‌شناختی\n\n` +
`درصدهای پیمایش exhaustive، **احتمال تجربی وقوع در جهان واقعی نیستند**. این درصدها سهم ترکیب‌های تصمیمی در فضای مدل هستند. جدول وزن‌دار نیت نیز فقط یک شاخص طراحی است که وزن‌های تعریف‌شده برای نیت پنهان را روی سهم‌های شرطی اعمال می‌کند و همچنان رفتار واقعی بازیکنان را مدل نمی‌کند.\n\n` +
`## پیمایش ساختاری\n\n` +
`- کل مسیرها: ${structuralTotal.toLocaleString()}\n` +
`- پایان‌های قابل دستیابی: ${overallRows.filter((r: any) => r.reachable).length} از ${END_STATES.length}\n` +
`- آنتروپی نرمال‌شده پایان‌ها: ${normalizedEntropy.toFixed(4)}\n` +
`- HHI: ${hhi.toFixed(4)}\n\n` +
`| پایان | تعداد | سهم از مسیرها |\n|---|---:|---:|\n` +
 topOverall.map((r: any) => `| ${r.end_state_fa} | ${Number(r.count).toLocaleString()} | ${r.percent}٪ |`).join("\n") +
`\n\n## نکته برای گزارش\n\n` +
`برای گزارش نهایی، پیشنهاد می‌شود سه نوع عدد از هم تفکیک شوند: (۱) reachability و سهم ساختاری مسیرها، (۲) سهم طراحی وزن‌دار بر اساس نیت‌های پنهان، و (۳) دامنه تغییر بین جهان‌های بذرثابت برای سنجش robustness. هیچ‌یک بدون داده تجربی رفتار کاربران نباید به‌عنوان «احتمال واقعی» معرفی شوند.\n`;
fs.writeFileSync(path.join(outDir, "report-ready-summary-fa.md"), md, "utf8");

const methodology = `# روش‌شناسی شبیه‌سازی برای گزارش طراحی سناریو ۴\n\n` +
`1. **پیمایش ساختاری exhaustive:** تمام تصمیم‌های اثرگذار بر پایان سناریو با adjudicatorهای واقعی تولید اجرا می‌شوند. reasonها و sliderهای انتساب در صورتی ثابت می‌مانند که بر primary End State اثر نداشته باشند.\n` +
`2. **درصدهای ساختاری:** نسبت تعداد مسیرهای منتهی به هر پایان به کل مسیرهای اجراشده است. این شاخص احتمال واقعی رخداد نیست، زیرا گزینه‌های بازیکن در فضای exhaustive به‌طور ساختاری enumerate می‌شوند.\n` +
`3. **سهم وزن‌دار نیت:** سهم شرطی هر پایان در هر intent ابتدا درون همان intent نرمال می‌شود و سپس وزن‌های طراحی 30/25/20/15/10 اعمال می‌شوند. این شاخص برای تحلیل طراحی مفید است، نه پیش‌بینی جهان واقعی.\n` +
`4. **توزیع policy-neutral وزن‌دار:** اگر all-paths ارائه شود، به هر intent وزن طراحی 30/25/20/15/10 داده می‌شود و برای گزینه‌های بازیکن انتخاب یکنواخت فرض می‌شود. چون off-ramp یک سؤال شرطی چهارگزینه‌ای است، هر برگ آن وزن 1/4 می‌گیرد تا صرفاً به‌دلیل افزایش تعداد برگ‌ها بیش‌وزن نشود. این شاخص همچنان احتمال تجربی واقعی نیست.\n` +
`5. **Robustness بین جهان‌ها:** اجرای چند world deterministic نشان می‌دهد seed، علت پنهان رخداد و noise بازیگران تا چه حد سهم پایان‌ها را تغییر می‌دهد.\n` +
`6. **تحلیل ارتباط گزینه–پایان:** در صورت ارائه all-paths.csv.gz، P(end|option) و lift محاسبه می‌شود. این یک association در فضای مدل است و نباید بدون تحلیل مکانیزم به‌صورت علی تفسیر شود.\n` +
`7. **منابع و confidence:** توزیع منابع و Attribution Confidence از summary تولید خوانده می‌شود و برای نشان‌دادن trade-off، scarcity و گستره عدم‌قطعیت استفاده می‌شود.\n`;
fs.writeFileSync(path.join(outDir, "methodology-fa.md"), methodology, "utf8");

console.log(`Done. Report analysis written to: ${outDir}`);
console.log(`Structural paths: ${structuralTotal.toLocaleString()}`);
console.log(`Reachable end states: ${overallRows.filter((r: any) => r.reachable).length}/${END_STATES.length}`);
if (pathsGzPath) console.log("Full-path association tables were generated.");
else console.log("No --paths supplied: summary-level tables only.");
